#!/usr/bin/env python3
"""Verify an interface handover (Codex's handover/p2p-interfaces.yaml) against live Zabbix.

    ./scripts/ingest-handover.py ../handover/p2p-interfaces.yaml [--env lab] [--out config/interfaces.yaml]
    GRAFANA_URL=.. GRAFANA_USER=.. GRAFANA_PASSWORD=.. ./scripts/ingest-handover.py FILE --via-grafana-proxy

Read-only. Every selected interface is cross-checked live (host exists/enabled/SNMP interface, interface
name present, host id, status item id, item's `interface` tag and SNMP index). Verified entries go to
--out; anything that fails, plus the entries the handover itself lists as review-required, goes to
REVIEW-REQUIRED.md next to it. Nothing is guessed and nothing is written to Zabbix.
"""
import argparse
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

import yaml                                                    # noqa: E402

from netalert import config, envsafety, handover               # noqa: E402
from netalert.zbx import HttpTransport, ZabbixClient           # noqa: E402

BASE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")


def handover_review_titles(path):
    p = os.path.join(os.path.dirname(os.path.abspath(path)), "p2p-review-required.md")
    if not os.path.isfile(p):
        return []
    with open(p, encoding="utf-8") as fh:
        return [m.group(1).strip() for m in re.finditer(r"^##\s+\d+\.\s+(.+)$", fh.read(), re.M)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("handover")
    ap.add_argument("--env", default="lab")
    ap.add_argument("--out", default=os.path.join(BASE, "config", "interfaces.generated.yaml"))
    ap.add_argument("--via-grafana-proxy", action="store_true",
                    help="dev only: read through the Grafana datasource proxy instead of the env token")
    a = ap.parse_args()
    if not os.path.isfile(a.handover):
        print("handover file not found: %s — nothing to do (do not guess production interfaces)" % a.handover)
        return 2
    if a.via_grafana_proxy:
        from devtools.grafana_proxy import GrafanaProxyTransport
        c = ZabbixClient(GrafanaProxyTransport(os.environ["GRAFANA_URL"], os.environ["GRAFANA_USER"],
                                               os.environ["GRAFANA_PASSWORD"],
                                               os.environ.get("GRAFANA_DS", "zabbix-lab")), read_only=True)
        print("Zabbix API %s (via Grafana read proxy; identity gate skipped: dev read-only)" % c.version())
    else:
        env = envsafety.load_env(BASE, a.env)
        url, token = envsafety.resolve_target(env)
        c = ZabbixClient(HttpTransport(url, token, env["zabbix"].get("verify_tls", True)), read_only=True)
        ident = envsafety.verify(BASE, env, c, url)
        if not ident.ok:
            print("environment safety check failed: %s" % "; ".join(ident.messages))
            return 3
    with open(a.handover, encoding="utf-8") as fh:
        raw = yaml.safe_load(fh)
    extras = None
    if handover.is_codex_format(raw):
        n_in = sum(len(h["interfaces"]) for h in raw["hosts"].values())
        data, extras = handover.from_codex(raw)
    else:
        data = handover.normalize(raw)
        n_in = sum(len(h["interfaces"]) for h in data["hosts"].values())
    verified, review, checks = handover.verify(c, data, extras)
    n_ok = sum(len(h["interfaces"]) for h in verified["hosts"].values())
    header = ("# LAB policy generated by scripts/ingest-handover.py from %s\n"
              "# %d/%d handover interfaces verified live. Both ends of every link notify; link_id is shared.\n"
              % (os.path.basename(a.handover), n_ok, n_in))
    with open(a.out, "w", encoding="utf-8") as fh:
        fh.write(handover.render_policy(verified, header))
    # sanity: the generated policy must pass our own strict validation
    problems = config.load(a.out).problems
    pre = handover_review_titles(a.handover)
    rpath = os.path.join(os.path.dirname(os.path.abspath(a.out)), "REVIEW-REQUIRED.md")
    text = ["# REVIEW REQUIRED", "",
            "Not enabled. Do not add these to the policy until the reason is resolved.", "",
            "## Excluded by the handover itself (%d)" % len(pre), ""]
    text += ["- %s" % t for t in pre] or ["- none"]
    text += ["", "## Failed the live Zabbix cross-check (%d)" % len(review), ""]
    text += ["- `%s` / `%s` — %s" % r for r in review] or ["- none"]
    with open(rpath, "w", encoding="utf-8") as fh:
        fh.write("\n".join(text) + "\n")
    print("handover entries: %d | verified live: %d | failed cross-check: %d | pre-excluded by handover: %d"
          % (n_in, n_ok, len(review), len(pre)))
    print("policy -> %s (valid: %s)" % (a.out, "yes" if not problems else "NO: %s" % problems[0].message))
    for host, iface, why in review:
        print("  REVIEW  %s / %s  %s" % (host, iface, why))
    return 0 if (not review and not problems) else 1


if __name__ == "__main__":
    sys.exit(main())
