#!/usr/bin/env python3
"""Verify an interface handover (e.g. Codex's handover/p2p-interfaces.yaml) against live Zabbix.

    ./scripts/ingest-handover.py ../handover/p2p-interfaces.yaml [--env lab] [--out config/interfaces.generated.yaml]

Read-only. Writes the verified subset to --out and the rest to REVIEW-REQUIRED.md next to it.
Then:  cp that file over config/interfaces.yaml (after reading it), ./apply.sh --check, --dry-run, apply.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

import yaml                                                    # noqa: E402

from netalert import config, envsafety, handover               # noqa: E402
from netalert.zbx import HttpTransport, ZabbixClient           # noqa: E402

BASE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("handover")
    ap.add_argument("--env", default="lab")
    ap.add_argument("--out", default=os.path.join(BASE, "config", "interfaces.generated.yaml"))
    a = ap.parse_args()
    if not os.path.isfile(a.handover):
        print("handover file not found: %s — nothing to do (do not guess production interfaces)" % a.handover)
        return 2
    env = envsafety.load_env(BASE, a.env)
    url, token = envsafety.resolve_target(env)
    c = ZabbixClient(HttpTransport(url, token, env["zabbix"].get("verify_tls", True)), read_only=True)
    ident = envsafety.verify(BASE, env, c, url)
    if not ident.ok:
        print("environment safety check failed: %s" % "; ".join(ident.messages))
        return 3
    with open(a.handover, encoding="utf-8") as fh:
        data = handover.normalize(yaml.safe_load(fh))
    verified, review, checks = handover.verify(c, data)
    n_ok = sum(len(h["interfaces"]) for h in verified["hosts"].values())
    header = "# GENERATED by scripts/ingest-handover.py from %s — review before use.\n" % os.path.basename(a.handover)
    with open(a.out, "w", encoding="utf-8") as fh:
        fh.write(handover.render_policy(verified, header))
    rpath = os.path.join(os.path.dirname(a.out), "REVIEW-REQUIRED.md")
    with open(rpath, "w", encoding="utf-8") as fh:
        fh.write(handover.render_review(review))
    print("verified %d interface(s) -> %s" % (n_ok, a.out))
    print("REVIEW REQUIRED: %d entr%s -> %s" % (len(review), "y" if len(review) == 1 else "ies", rpath))
    for host, iface, why in review:
        print("  REVIEW  %s / %s  %s" % (host, iface, why))
    return 0 if not review else 1


if __name__ == "__main__":
    sys.exit(main())
