const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');const{spawn}=require('node:child_process');
const fixture=path.resolve(process.argv[2]||''),evidence=path.resolve(process.argv[3]||path.join(os.tmpdir(),'device-health-browser'));const chrome=process.env.CHROME_PATH||'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';if(!fs.existsSync(fixture)||!fs.existsSync(chrome))throw new Error('fixture or Chrome missing');fs.mkdirSync(evidence,{recursive:true});const profile=fs.mkdtempSync(path.join(os.tmpdir(),'dh-chrome-'));const child=spawn(chrome,['--headless=new','--disable-gpu','--no-first-run','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{stdio:'ignore'});const pause=ms=>new Promise(r=>setTimeout(r,ms));let ws,seq=0;const pending=new Map(),exceptions=[];
function cmd(method,params={}){return new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));setTimeout(()=>{if(pending.has(id)){pending.delete(id);reject(new Error(method+' timeout'));}},15000);});}async function evaljs(expression){const r=await cmd('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.text);return r.result.value;}const check=(n,a,e)=>{assert.deepEqual(a,e,n);console.log('PASS '+n);};async function shot(n){const s=await cmd('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(evidence,n+'.png'),Buffer.from(s.data,'base64'));}
(async()=>{for(let i=0;i<100&&!fs.existsSync(path.join(profile,'DevToolsActivePort'));i++)await pause(100);const port=fs.readFileSync(path.join(profile,'DevToolsActivePort'),'utf8').split('\n')[0];const target=(await(await fetch(`http://127.0.0.1:${port}/json`)).json()).find(x=>x.type==='page');ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(new Error(JSON.stringify(m.error))):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')exceptions.push(m.params.exceptionDetails.text);};await cmd('Runtime.enable');await cmd('Page.enable');await cmd('Page.navigate',{url:'file:///'+fixture.replaceAll('\\','/')});await pause(500);
check('matrix devices',await evaljs(`document.querySelectorAll('.dh-table tbody tr').length`),5);check('attention dedup count',await evaljs(`document.querySelectorAll('.dh-attention-row').length`),3);
await evaljs(`(()=>{const x=document.querySelector('.dh-search');x.value='linux';x.dispatchEvent(new Event('input',{bubbles:true}));})()`);check('search',await evaljs(`[...document.querySelectorAll('.dh-table tbody tr')].filter(x=>!x.hidden).map(x=>x.dataset.deviceId)`),['3']);await evaljs(`(()=>{const x=document.querySelector('.dh-search');x.value='';x.dispatchEvent(new Event('input',{bubbles:true}));})()`);
await evaljs(`(()=>{const x=document.querySelector('.dh-site-filter');x.value='DR';x.dispatchEvent(new Event('change',{bubbles:true}));})()`);check('site filter',await evaljs(`[...document.querySelectorAll('.dh-table tbody tr')].filter(x=>!x.hidden).map(x=>x.dataset.deviceId)`),['4','5']);await evaljs(`(()=>{const x=document.querySelector('.dh-site-filter');x.value='';x.dispatchEvent(new Event('change',{bubbles:true}));})()`);
await evaljs(`document.querySelector('[data-summary-filter="CRITICAL"]').click()`);check('summary filter',await evaljs(`[...document.querySelectorAll('.dh-table tbody tr')].filter(x=>!x.hidden).map(x=>x.dataset.deviceId)`),['1']);await evaljs(`document.querySelector('[data-summary-filter="CRITICAL"]').click()`);
await evaljs(`document.querySelector('.dh-sort').value='cpu';document.querySelector('.dh-sort').dispatchEvent(new Event('change',{bubbles:true}))`);check('sort',await evaljs(`[...document.querySelectorAll('.dh-table tbody tr')].map(x=>x.dataset.deviceId)[0]`),'1');
await evaljs(`document.querySelector('.dh-site__header').click()`);check('site collapse',await evaljs(`document.querySelector('.dh-site').classList.contains('is-collapsed')`),true);await evaljs(`document.querySelector('.dh-site__header').click()`);
await evaljs(`document.querySelector('[data-device-details="2"]').click()`);check('details paired rows',await evaljs(`[...document.querySelectorAll('.dh-detail-row')].every(x=>x.children.length===2)`),true);check('unknown profile visible',await evaljs(`document.querySelector('.dh-details').textContent.includes('Not mapped')`),true);await evaljs(`document.querySelector('.dh-panel-close').click()`);
for(const theme of ['blue','dark']){await evaljs(`document.body.classList.toggle('dark',${theme==='dark'});document.querySelector('.netops-device-health').classList.toggle('is-dark-theme',${theme==='dark'})`);for(const width of [2200,1920,1440,1200,900,640,420]){await cmd('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:false});await pause(120);const l=await evaljs(`(()=>{const r=document.querySelector('.netops-device-health'),a=[...document.querySelectorAll('.dh-attention-row')];return{overflow:document.documentElement.scrollWidth>innerWidth+1,attentionOverlap:a.some((x,i)=>i&&x.getBoundingClientRect().top<a[i-1].getBoundingClientRect().bottom),content:r.querySelector('.dh-content').getBoundingClientRect().width};})()`);check(`${theme} ${width} no overflow`,l.overflow,false);check(`${theme} ${width} attention no overlap`,l.attentionOverlap,false);if([2200,1200,640,420].includes(width))await shot(`device-health-${theme}-${width}`);}}
check('browser exceptions',exceptions,[]);console.log('BROWSER=PASS EVIDENCE='+evidence);
})().catch(e=>{console.error('BROWSER=FAIL',e.stack||e);process.exitCode=1}).finally(()=>{try{ws?.close();child.kill()}catch{}});
