<?php declare(strict_types = 1);
if(($argc??0)!==2){fwrite(STDERR,"usage: php ui_fixture.php OUTPUT.html\n");exit(2);} $module=dirname(__DIR__,2).'/frontend/modules/DeviceHealth';
class CTag {private array $items=[],$attrs=[];public function __construct(private string $tag,private bool $closed=true,mixed $items=[]){$this->addItem($items);}public function addItem(mixed $item):self{if(is_array($item))foreach($item as $part)$this->addItem($part);elseif($item!==null)$this->items[]=$item;return $this;}public function addClass(string $c):self{$this->attrs['class']=trim(($this->attrs['class']??'').' '.$c);return $this;}public function setAttribute(string $k,mixed $v):self{$this->attrs[$k]=(string)$v;return $this;}public function __toString():string{$a='';foreach($this->attrs as $k=>$v)$a.=' '.htmlspecialchars($k).'="'.htmlspecialchars($v).'"';$body='';foreach($this->items as $i)$body.=$i instanceof self?(string)$i:htmlspecialchars((string)$i);return '<'.$this->tag.$a.'>'.($this->closed?$body.'</'.$this->tag.'>':'');}}
class CDiv extends CTag{public function __construct(mixed $i=[]){parent::__construct('div',true,$i);}}class CSpan extends CTag{public function __construct(mixed $i=[]){parent::__construct('span',true,$i);}}class CWidgetView{private array $items=[];public function __construct(private array $data){}public function addItem(mixed $i):self{$this->items[]=$i;return $this;}public function show():void{foreach($this->items as $i)echo $i;}}
$now=1800000000;$metric=function($value,$units='%',$severity=0,$state='CURRENT',$details=[])use($now){return ['state'=>$state,'data_state'=>$state,'value'=>$value,'units'=>$units,'severity'=>$severity,'grace_active'=>false,'clock'=>$now-30,'age'=>30,'details'=>$details];};
$devices=[];foreach([
	['1','CORE-RTR-01','CENT-NETWORK','router_switch','CRITICAL',4,95,61],['2','LONG-DEVICE-NAME-WITH-MULTIPLE-SEGMENTS-AND-OPERATIONS-SUFFIX','CENT-NETWORK','unknown','WARNING',2,65,78],
	['3','LINUX-APP-01','CENT-NETWORK','linux_host','HEALTHY',0,13,44],['4','FW-DR-01','DR','firewall','UNKNOWN',1,null,null],['5','LOAD-BALANCER-01','DR','load_balancer','HEALTHY',0,18,50]
] as [$id,$name,$site,$profile,$state,$severity,$cpu,$memory]){$cols=[];foreach(['cpu','memory','temperature','storage','power_fan','ha'] as $k){$value=$k==='cpu'?$cpu:($k==='memory'?$memory:($k==='storage'?54:null));$data=$value===null?($profile==='unknown'?'NOT_APPLICABLE':'NO_DATA'):'CURRENT';$cols[$k]=$metric($value,$value===null?'':'%',$k==='cpu'?$severity:0,$data,$k==='storage'?[['name'=>'FS [/boot]','mount'=>'/boot','value'=>25,'units'=>'%','freshness'=>['state'=>'CURRENT']],['name'=>'FS [/]','mount'=>'/','value'=>54,'units'=>'%','freshness'=>['state'=>'CURRENT']]]:[]);}
	$issues=$severity>=2?[['id'=>'p'.$id,'name'=>$severity>=4?'High CPU utilization':'Memory pressure','severity'=>$severity,'clock'=>$now-7200,'acknowledged'=>false,'suppressed'=>false,'category'=>$severity>=4?'cpu':'memory','device_id'=>$id,'device'=>$name,'site'=>$site,'itemids'=>[],'hostids'=>[$id]]]:[];
	$devices[]=['hostid'=>$id,'host'=>strtolower($name),'name'=>$name,'site'=>$site,'profile'=>$profile,'profile_status'=>$profile==='unknown'?'UNRESOLVED':'MAPPED','capabilities'=>[],'maintenance'=>false,'availability'=>$state==='UNKNOWN'?'UNKNOWN':'UP','metrics'=>[],'metric_details'=>[],'issues'=>$issues,'columns'=>$cols,'severity'=>$severity,'state'=>$state,'reasons'=>array_column($issues,'name')];}
$attention=[];foreach($devices as $d)foreach($d['issues'] as $i)$attention[]=$i;$attention[]=['id'=>'data4','name'=>'CPU STALE','severity'=>1,'clock'=>$now-4000,'acknowledged'=>false,'suppressed'=>false,'category'=>'data','device_id'=>'4','device'=>'FW-DR-01','site'=>'DR'];
$data=['error'=>null,'snapshot'=>['generated_at'=>$now,'summary'=>['CRITICAL'=>1,'WARNING'=>1,'RESOURCE'=>2,'HARDWARE'=>0,'HA'=>0,'UNKNOWN_STALE'=>1,'MONITORED'=>5],'needs_attention'=>$attention,'devices'=>$devices,'sites'=>['CENT-NETWORK'=>array_slice($devices,0,3),'DR'=>array_slice($devices,3)]],'warnings'=>[],'instrumentation'=>['api_call_count'=>4,'collector_time_ms'=>72,'resolver_time_ms'=>.7,'total_widget_time_ms'=>75]];
ob_start();include $module.'/views/widget.view.php';$markup=ob_get_clean();
$bootstrap=<<<'JS'
class CWidget{constructor(){this._contents=document.getElementById('mount');}setContents(html){this._contents.innerHTML=html;}onClearContents(){}};
JS;
$html='<!doctype html><html><head><meta charset="utf-8"><title>Device Health fixture</title><style>body{margin:0;padding:8px;background:#fff;font:13px Arial}body.dark{background:#20272d}#mount{width:100%}button,input,select{font:inherit}</style><style>'.file_get_contents($module.'/assets/css/device-health.css').'</style></head><body><div id="mount"></div><template id="markup">'.$markup.'</template><script>'.$bootstrap.'</script><script>'.file_get_contents($module.'/assets/js/class.widget.js').'</script><script>window.widget=new CWidgetDeviceHealth();window.widget.setContents(document.getElementById("markup").innerHTML);</script></body></html>';
file_put_contents($argv[1],$html);echo "FIXTURE=PASS\n";
