"""The Cisco definitions are checked against the Cisco-published MIB files (docs/sources/cisco-mib-extract.json, generated by
docs/sources/extract-cisco-mibs.py from github.com/cisco/cisco-mibs): every OID and every enumeration name must match the MIB."""
import json
import os
import unittest

from hwh import vendordefs

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFS = vendordefs.load_dir(os.path.join(ROOT, "vendors"))
with open(os.path.join(ROOT, "docs", "sources", "cisco-mib-extract.json"), encoding="utf-8") as fh:
    MIB = json.load(fh)
OBJ = MIB["objects"]
STANDARD = {"entPhysicalName": "1.3.6.1.2.1.47.1.1.1.1.7"}     # ENTITY-MIB (RFC 6933), not part of the Cisco repository


def bare(name):
    return name.split("::")[-1]


class CiscoMibs(unittest.TestCase):
    def test_extract_provenance(self):
        self.assertEqual(len(MIB["source"]["commit"]), 40)
        for f in MIB["source"]["files"].values():
            self.assertEqual(len(f["sha256"]), 64)
            self.assertIn(MIB["source"]["commit"], f["url"])

    def test_every_oid_matches_the_mib(self):
        checked = 0
        for did in ("cisco-iosxe", "cisco-nxos"):
            for sn in DEFS[did]["sensors"]:
                v, t = sn["value"], sn["table"]
                self.assertIn(bare(v["object"]), OBJ, "%s/%s value object not in the MIB extract" % (did, sn["id"]))
                self.assertEqual(v["oid"], OBJ[bare(v["object"])]["oid"], "%s/%s value OID" % (did, sn["id"]))
                n = bare(t["name_object"])
                self.assertEqual(t["name_oid"], OBJ[n]["oid"] if n in OBJ else STANDARD[n], "%s/%s name OID" % (did, sn["id"]))
                checked += 2
        self.assertGreaterEqual(checked, 14)

    def test_every_enumeration_matches_the_mib(self):
        seen = set()
        for did in ("cisco-iosxe", "cisco-nxos"):
            d = DEFS[did]
            for sn in d["sensors"]:
                if sn["scope"] == "reading":
                    continue
                sem = d["semantics"][sn["value"]["semantics"]]
                enum = OBJ[bare(sn["value"]["object"])]["enum"]
                self.assertEqual(sorted(sem["states"], key=int), sorted(enum, key=int), "%s: raw values differ from the MIB" % sn["id"])
                for raw, st in sem["states"].items():
                    self.assertEqual(st["meaning"], enum[str(raw)], "%s raw %s" % (sn["id"], raw))
                seen.add(sn["value"]["semantics"])
        self.assertEqual(seen, {"cisco-envmon-state", "cisco-cefc-fan-tray", "cisco-cefc-fru-power", "cisco-entsensor-status"})

    def test_mib_documents_what_the_classification_relies_on(self):
        # fan-tray warning = "partial failure, needs replacement as soon as possible" (MIB text), so it is degraded not failed
        d = DEFS["cisco-nxos"]["semantics"]["cisco-cefc-fan-tray"]["states"]
        self.assertEqual(d["4"]["state"], "degraded")
        self.assertEqual(d["3"]["state"], "failed")


if __name__ == "__main__":
    unittest.main()


class FortinetHuaweiMibs(unittest.TestCase):
    """Fortinet / Huawei definitions vs the vendor MIB text (a third-party mirror, recorded as such in the extract)."""
    MIB2 = None

    @classmethod
    def setUpClass(cls):
        with open(os.path.join(ROOT, "docs", "sources", "vendor-mib-extract.json"), encoding="utf-8") as fh:
            cls.MIB2 = json.load(fh)

    def test_provenance_is_pinned_and_labelled_third_party(self):
        s = self.MIB2["source"]
        self.assertEqual(len(s["commit"]), 40)
        self.assertIn("third-party", s["note"])

    def test_oids_and_enumerations_match(self):
        o = self.MIB2["objects"]
        for did in ("fortinet-fortigate", "huawei-vrp"):
            d = DEFS[did]
            for sn in d["sensors"]:
                v = sn["value"]
                name = bare(v["object"])
                self.assertEqual(v["oid"], o[name]["oid"], "%s/%s" % (did, sn["id"]))
                t = sn.get("table") or {}
                if bare(t.get("name_object", "")) in o:
                    self.assertEqual(t["name_oid"], o[bare(t["name_object"])]["oid"])
                if sn["scope"] == "reading":
                    continue
                sem = d["semantics"][v["semantics"]]
                enum = o[name]["enum"]
                self.assertEqual(sorted(sem["states"], key=int), sorted(enum, key=int), sn["id"])
                for raw, st in sem["states"].items():
                    self.assertEqual(st["meaning"], enum[str(raw)], "%s raw %s" % (sn["id"], raw))
