#!/usr/bin/env bash
set -Eeuo pipefail
DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")"&&pwd -P);ROOT=$(cd "$DIR/.."&&pwd -P);source "$DIR/lib/device-health-common.sh"
PREFLIGHT=0;[[ ${1:-} == --preflight && $# -eq 1 ]]&&PREFLIGHT=1||[[ $# -eq 0 ]]||dh_fail 'usage: install-device-health.sh [--preflight]'
dh_need sha256sum;dh_environment;SRC="$ROOT/frontend/modules/DeviceHealth";dh_release "$SRC";dh_info "OS=$DH_OS";dh_info "ZABBIX_VERSION=$DH_ZABBIX";dh_info "PHP_VERSION=$DH_PHP_VERSION";dh_info "MODULES_DIR=$DH_MODULES";((PREFLIGHT))&&{ dh_info PREFLIGHT=PASS;exit 0; }
dh_root;dh_identity;RUNTIME=${DEVICE_HEALTH_RUNTIME_DIR:-/var/lib/zabbix/device-health};install -d -o "$DH_USER" -g "$DH_GROUP" -m 0750 "$RUNTIME";CONFIG="$RUNTIME/device-health.json"
if [[ -r $CONFIG ]];then dh_config "$SRC" "$CONFIG";chown "$DH_USER:$DH_GROUP" "$CONFIG";chmod 0640 "$CONFIG";dh_info RUNTIME_CONFIGURATION=PRESERVED;else install -o "$DH_USER" -g "$DH_GROUP" -m 0640 "$SRC/config/device-health.json" "$CONFIG";dh_info RUNTIME_CONFIGURATION=INITIALIZED;fi
[[ -e $RUNTIME/first-observed.json ]]&&{ chown "$DH_USER:$DH_GROUP" "$RUNTIME/first-observed.json";chmod 0640 "$RUNTIME/first-observed.json";}||true
if command -v selinuxenabled>/dev/null&&selinuxenabled;then dh_need semanage;dh_need restorecon;semanage fcontext -a -t httpd_sys_rw_content_t "$RUNTIME(/.*)?" 2>/dev/null||semanage fcontext -m -t httpd_sys_rw_content_t "$RUNTIME(/.*)?";restorecon -RF "$RUNTIME";fi
TARGET="$DH_MODULES/DeviceHealth";OWNER=$(stat -c %U "$DH_MODULES");GROUP=$(stat -c %G "$DH_MODULES");STAGE=$(mktemp -d "$DH_MODULES/.DeviceHealth.install.XXXXXX");trap '[[ -n ${STAGE:-} && -d $STAGE ]] && rm -rf -- "$STAGE"' EXIT;cp -a "$SRC/." "$STAGE/";chown -R "$OWNER:$GROUP" "$STAGE";find "$STAGE" -type d -exec chmod 0755 {} +;find "$STAGE" -type f -exec chmod 0644 {} +;dh_release "$STAGE";STAMP=$(date -u +%Y%m%d-%H%M%S);BACKUP='';[[ -d $TARGET ]]&&{ BACKUP="$DH_MODULES/DeviceHealth.backup-$STAMP";mv "$TARGET" "$BACKUP";};mv "$STAGE" "$TARGET"||{ [[ -n $BACKUP ]]&&mv "$BACKUP" "$TARGET"||true;dh_fail 'activation failed';};STAGE='';command -v restorecon>/dev/null&&restorecon -RF "$TARGET"||true;dh_info "INSTALLED=$TARGET";dh_info "RUNTIME=$RUNTIME";dh_info SERVICE_RESTARTS=NONE;dh_info PASS
